### ISSUE TITLE
The "Engine Development" Release Features Issue

### ISSUE THREAD

**Issue by ennukee** [umts/microservices-engine#5]
# Microservices-engine
## TO-DO

Removed 9/29/2016: The initializer will no longer need a valid verification flag (it will only matter if someone registers an existing / future model externally before the services can, in which case the object can be deleted remotely)
- [x] Remove part of the engine endpoint that returns data (the microservice will have its own endpoints)
  - [x] Including the generator that generates the config initializer
  - [x] Also remove the Config (no longer necessary)
- [ ] Add endpoint that receives data from the `microservices-router`. Requires a valid verification flag to properly accept the request.
  - [x] Add skeleton code for the verification / receiving process (as this requires router being near completion)
  - [ ] Implement a verification flag methodology (requires collab w/ `router`)
  - [x] Implement the data-receiving-from-router methology
- [x] New Engine Generator
  - [x] Make a template YAML file (empty by default)
  - [x] Have the template YAML be copied to the main app when the generator is run
  - [x] Have it copy an initializer that will send the YAML file's data to `microservices-engine`. Again, this requires a valid verification flag.
- [x] The Initializer
  - [x] Read from YAML file
  - [x] Send data from YAML file to `microservices-router`
  - [x] However, do not send anything if the YAML file is not filled out yet
  - [x] Warn the user of main app startup that the engine is not yet registered.

Once we know how everything will really look, we have...
- [ ] TESTS
  - [x] DataController (endpoint) tests
  - [ ] Connection model tests
  - [x] Engine tests

**Comment by dfaulken** [comment]
Seems like perhaps this [could be a project](https://github.com/umts/microservices-engine/projects)?

**Comment by ennukee** [comment]
That's a fun feature, didn't know that existed.

edit: on further inspection, the UI is a bit wonky, it doesn't seem to support checklists at all?

**Comment by werebus** [comment]
Yeah, they rolled it out at the same time as the new code-review stuff.
